### ISSUE TITLE
Whether to check the similarity before audio storage

### ISSUE THREAD

**Issue by 980202006** [mimbres/neural-audio-fp#16]
Whether to check the similarity before audio storage?
Is there a simple demo for query and other operations ?

**Comment by Mihonarium** [comment]
@mimbres, I think it would be convenient to have an interface for managing a simple DB with adding/deleting songs and matching new audio against the DB. If you're not already working on this, let me know, I can help

**Comment by mimbres** [comment]
@Mihonarium I am **not** already working on it. I have thought your [notebook] (https://gist.github.com/Mihonarium/e3fd355cb560b82373fd2186139f1bc2) was awesome. I will appreciate your help:) We can add  features on it.

**Comment by 980202006** [comment]
Thank you!I try to expose the interface.
