### ISSUE TITLE
Get fingerprints for custom wav input files

### ISSUE THREAD

**Issue by ac-alpha** [mimbres/neural-audio-fp#21]
I want to generate just the fingerprints for custom wav file as input. I just want to generate fingerprint for one single wav file. Could someone point me to a script which can do so. 
e.g. If I have a wav file of 10s and my seg length is 1s and hop 0.5s, then I want a fingerprint output of size `(19 x fp_dim)`.

**Comment by mimbres** [comment]
@ac-alpha It is briefly described in [readme/More Features/Fingerprint Generation](https://github.com/mimbres/neural-audio-fp#more-features).
```
python run.py generate --source SOURCE_ROOT_DIR --output FP_OUTPUT_DIR --skip_dummy # for custom audio source
python run.py generate --help # more details...
```

**Comment by ac-alpha** [comment]
Thanks @mimbres. The script above ignores the last `(total_segments%test_bsz)` segments of the wav file, so I was not sure if the script is correct or not.

**Comment by mimbres** [comment]
@ac-alpha Thanks for reporting the issue. The problem with the last segments `(total_seg%test_bsz)` being dropped is an expected error.  
- A quick trick to avoid this is to modify `TS_BATCH_SZ` parameter in the config file as a divisible number.
- Fixing this problem will be reflected in the next update.
