### ISSUE TITLE
Could you please provide the checksum of fma_full only? 

### ISSUE THREAD

**Issue by SineX8** [mimbres/neural-audio-fp#25]
or checksum of other files separately so that I can locate the different files...

**Comment by SineX8** [comment]
@mimbres Please provide the checksum of fma_full directory of this project first and that can help me indeed. It will be fine if this directory is correct in my situation. I've checked the numbers of files in your google drive and my disk and they're the same. However the number (about 54M) of segments generated in my evaluation experiment with window length of 1s and hop of 0.5s is different from yours (about 56M) stated in the paper. So I'm wondering if there's something wrong with my dummy dataset.

**Comment by mimbres** [comment]
@SineX8 Got it!

**Comment by mimbres** [comment]
@SineX8 https://drive.google.com/drive/folders/1Bqy5Xsxh4ArmcWsKfQOBpp-sJIVU8UG5?usp=sharing
I'm also checking the number of segments generated based on this version of dataset. Because I remember the number was different from I stated in the paper. Sorry for inconvenience.

**Comment by SineX8** [comment]
@mimbres Thank you for your help! I also want to know whether your results reported in your paper were based on this version of dataset?

**Comment by mimbres** [comment]
@SineX8 No. I found some duplicates between test and dummy.

**Comment by SineX8** [comment]
@mimbres So it's reasonable that the results I obtained using your model was better than which you reported in your paper. Thanks for your help again!

**Comment by mimbres** [comment]
@SineX8 Yes, as reported in #18
