### ISSUE TITLE
IS THIS REPOSITORY HELPFUL FOR FOLLOWING SITUATION

### ISSUE THREAD

**Issue by kasireddygariDineshKumarReddy** [mimbres/neural-audio-fp#31]
Is this repository helpful for the below situation?
There could be situations where we need to detect the presence of new
sound sources for whose prerecorded acoustic signatures are available.
In order to handle such novel situations, the proposed system will be
equipped with audio search capability, which performs template
matching to detect the sound sources which match the given acoustic
signature (pre-recorded sound from that source).

**Comment by mimbres** [comment]
@kasireddygariDineshKumarReddy A simple answer is yes. Music copyright detection is one of the most common applications of audio fingerprinting, but it is not only limited to music sources. It can be useful for detecting a specific audio file from audio streams that contains some acoustic noise.
