### ISSUE TITLE
Model Definition Front Strides

### ISSUE THREAD

**Issue by daniel-deychakiwsky** [mimbres/neural-audio-fp#42]
Hey team! I'm looking into the model definition [here](https://github.com/mimbres/neural-audio-fp/blob/main/model/fp/nnfp.py#L194C18-L194C31). 

Should

```python
 front_strides=[[(1,2), (2,1)], [(1,2), (2,1)],
                [(1,2), (2,1)], [(1,2), (2,1)],
                [(1,1), (2,1)], [(1,2), (2,1)],
                [(1,1), (2,1)], [(1,2), (2,1)]],
```

be

```python
 front_strides=[[(1,2), (2,1)], [(1,2), (2,1)],
                [(1,2), (2,1)], [(1,2), (2,1)],
                [(1,2), (2,1)], [(1,2), (2,1)],
                [(1,2), (2,1)], [(1,2), (2,1)]],
```

Or is the former intended and, if so, why?

**Comment by mimbres** [comment]
@daniel-deychakiwsky I can't quite remember now, but there was likely no significant reason.

We reduced dimensions by using strides instead of pooling. Input shape was not square (T x F spectrogram, where T is not F), and continuously using [(1,2), (2,1)] would waste parameters.
