### ISSUE TITLE
UnboundLocalError in run.py during training

### ISSUE THREAD

**Issue by Rodrigo29Almeida** [mimbres/neural-audio-fp#43]
Hello,
I executed the following command:

python run.py train CHECKPOINT --max_epoch=100 -c default

The code is throwing the following error on line 207:
if cfg['TRAIN']['SAVE_IMG'] and sim_mtx is not None:
UnboundLocalError: local variable 'sim_mtx' referenced before assignment

I am facing this issue and not sure how to fix it. Any insights on what might be causing this error?

**Comment by mimbres** [comment]
@Rodrigo29Almeida 

Try setting SAVE_IMG to False in the config file. 
But I don't quite understand it, because the training should return the `sim_mtx` when calculating the loss at the first iteration.

**Comment by Rodrigo29Almeida** [comment]
Hello, thanks for your help before. I was a problem with a missing "/" in my path to the database. I apologize for the error.

I have installed an anaconda environement following your steps.

As I attempted to run the code in my environment, I encountered an issue in the trainer.py file, specifically in the train_step function. The problematic line is:
feat = m_specaug(m_pre(X))  # (nA+nP, F, T, 1)
The error message I received is as follows:
OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.

I am reaching out to seek your guidance on resolving this issue. Additionally, I want to inform you that I previously addressed a problem with len() in the same file. The error message was:
"len is not well defined for symbolic Tensors. (X:0) Please call `x.shape` rather than `len(x)` for shape information."
To resolve this, I modified the code from:
n_anchors = len(X[0])   to   n_anchors = X[0].shape[0]
I would greatly appreciate your assistance in understanding and resolving the current issue. If you have any suggestions or insights, it would be immensely helpful.

Thank you for your time.
