### ISSUE TITLE
Issue with Dependencies

### ISSUE THREAD

**Issue by tomashlehmann** [mimbres/neural-audio-fp#44]
Hello,
Thank you for sharing your code. I am attempting to reproduce your setup but am encountering persistent issues with dependencies. Could you please provide a requirements file with the specific versions of the libraries that are compatible with CUDA 11.2 and an RTX 3070?

**Comment by mimbres** [comment]
Duplicated issue:
https://github.com/mimbres/neural-audio-fp/issues/20#issuecomment-984449662
