### ISSUE TITLE
change audio fingerprints 

### ISSUE THREAD

**Issue by mishav78** [mimbres/neural-audio-fp#45]
Tell me how to change a song sufficiently that the audio fingerprint changes enough to make the song pass filters looking for duplicate songs. I'm looking for advice that works for most stringent filters. Tell me what to do, code, program already available or algorithm. Absolutely anything that works is acceptable.

**Comment by mimbres** [comment]
Hi mishav78,

It seems related to adversarial attacks, but it's out of scope for this repository. I hope you understand.
