### ISSUE TITLE
Custom Dataset Inquiries

### ISSUE THREAD

**Issue by jrnmapanao** [mimbres/neural-audio-fp#47]
Hello,

I'm trying to reproduce the code using my custom dataset as training (1000 unique full audio sets with varying lengths) and audio segments(100 segments of 15s) from the training as my evaluation:

1. Should I convert it explicitly to 16khz or 8khz?
2. What could be the possible setup for the installation of these custom datasets for training and evaluation?
3. I will not use the dataset on this project. What would be the setup?
4. After setting up the dataset, will other instructions be the same?

**Comment by mimbres** [comment]
@jrnmapanao 
1. 8 KHz
2-4. Please search the issue board using the term 'custom'.
Thanks.
