### ISSUE TITLE
use for streaming rtsp audio

### ISSUE THREAD

**Issue by haiderasad** [mimbres/neural-audio-fp#49]
How is the performance on real time audio detection given we have a database of selected music ?

**Comment by mimbres** [comment]
@haiderasad  This can be implemented as `quasi real-time since` it allows for search with just 1-5 seconds of input. Please refer to the result table in the paper. One of the industrial use cases is [here](https://play.google.com/store/apps/details?id=skplanet.musicmate&hl=en_GB).
